Fix Spell Stacking
mdingena/att-voodoo-server pull request #17
Opened 2022-04-26 17:18 UTC by OfficialExouls

I believe this should stop people from being able to cast multiple spells as well as account for the additive nature of the modify-stat command. what I mean by that is that the command, instead of setting the stat to the value you give it, it adds the value to the current stat, creating some unintended levels of speed. review it and deem if it's necessary to merge into the base repository.

2022-04-28 02:34 UTC, mdingena requested changes

2022-04-28 02:34 UTC, mdingena commented on src/voodoo/spellbook/spells/haste.ts
> +  const multiplier = attributes.intensify / 100;
Shouldn't call this a multiplier anymore if you remove the `1`.

```suggestion
  const bonus = attributes.intensify / 100;
```

2022-04-28 02:34 UTC, mdingena commented on src/voodoo/spellbook/spells/haste.ts
> +    if (baseSpeed == currentSpeed) {
I'd say that if a user is already under the influence of a normal speed potion but has a Haste invocation that would make them go even faster, Voodoo would make up for the difference.

With this current proposed change, once under the influence of any other speed effect, Haste does not work _at all_.

I'd suggest this

```suggestion
    const buffedSpeed = baseSpeed * (1 + bonus);
    const speedDelta = buffedSpeed - currentSpeed;

    if (speedDelta > 0) {
```

2022-04-28 02:34 UTC, mdingena commented on src/voodoo/spellbook/spells/haste.ts
>        const buffedSpeed = baseSpeed * multiplier;
Shouldn't call this the "buffed speed" anymore if it only represents an addition, not the new absolute speed stat.

```suggestion
      const speedBuff = baseSpeed * bonus;
```

There is more code below that is invalidated by these suggestions that you'd have to change for this PR.

2022-04-28 02:34 UTC, mdingena commented on src/voodoo/spellbook/spells/haste.ts
> +    const currentSpeed = await voodoo.getPlayerCheckStatCurrent({accountId: playerId, stat: 'speed' });
Because this represents two consecutive calls to `player check-stat`, I'd introduce a new method that gets both of these in a single call.

2022-04-28 04:51 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/stoneskin.ts
> +  const multiplier = attributes.intensify / 100;
Implementing mdingena's suggestions
```suggestion
  const bonus = attributes.intensify / 100;
```

2022-04-28 04:51 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/stoneskin.ts
> +    if (baseDamageProtection == currentDamageProtection) {
Implementing mdigena's suggestions
```suggestion
    const buffedDamageProtection = baseSpeed * (1 + bonus);
    
    const damageprotectionDelta = buffedDamageProtection - currentDamageProtection;
    
    
    if (damageprotectionDelta > 0) {
```

2022-04-28 04:51 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/stoneskin.ts
>        const buffedDamageProtection = baseDamageProtection * multiplier;
Implementing mdigena's suggestions
```suggestion
      const damageprotectionBuff = baseDamageProtection * bonus;
```

2022-04-28 04:51 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/trueStrike.ts
> +  const multiplier = attributes.intensify / 100;
Implementing mdigena's suggestions
```suggestion
  const bonus = attributes.intensify / 100;
```

2022-04-28 04:51 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/trueStrike.ts
>      if (baseDamage) {
Implementing mdigena's suggestions
```suggestion
    const buffedDamage = baseDamage * (1 + bonus);
    
    const damageDelta = buffedDamage - currentDamage;
    
    
    if (damageDelta > 0) {
```

2022-04-28 04:51 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/trueStrike.ts
>        const buffedDamage = baseDamage * multiplier;
Implementing mdigena's suggestions
```suggestion
      const damageBuff = baseDamage * bonus;
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/haste.ts
> +    const buffedSpeed = playerSpeed.base * (1 + bonus);
```suggestion
    const buffedSpeed = playerSpeed.Base * (1 + bonus);
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/haste.ts
> +    const speedDelta = buffedSpeed - playerSpeed.value;
```suggestion
    const speedDelta = buffedSpeed - playerSpeed.Value;
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/haste.ts
> +      const speedBuff = playerSpeed.base * bonus;
```suggestion
      const speedBuff = playerSpeed.Base * bonus;
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/stoneskin.ts
> +    const buffedDamageProtection = playerDamageProtection.base * (1 + bonus);
```suggestion
    const buffedDamageProtection = playerDamageProtection.Base * (1 + bonus);
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/stoneskin.ts
> +    const damageprotectionDelta = buffedDamageProtection - playerDamageProtection.value;
```suggestion
    const damageprotectionDelta = buffedDamageProtection - playerDamageProtection.Value;
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/stoneskin.ts
> +      const damageprotectionBuff = playerDamageProtection.base * bonus;
```suggestion
      const damageprotectionBuff = playerDamageProtection.Base * bonus;
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/trueStrike.ts
> +    const buffedDamage = playerDamage.base * (1 + bonus);
```suggestion
    const buffedDamage = playerDamage.Base * (1 + bonus);
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/trueStrike.ts
> +    const damageDelta = buffedDamage - playerDamage.value;
```suggestion
    const damageDelta = buffedDamage - playerDamage.Value;
```

2022-04-30 16:59 UTC, OfficialExouls commented on src/voodoo/spellbook/spells/trueStrike.ts
> +      const damageBuff = playerDamage.base * bonus;
```suggestion
      const damageBuff = playerDamage.Base * bonus;
```

2022-05-02 11:56 UTC, mdingena approved these changes
Nice work, mate! Thanks for the PR.

2022-05-02 11:56 UTC, merged